# Generated by Django 4.1.3 on 2022-11-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="group",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="like",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="like",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="is_deleted",
        ),
    ]
