# Generated by Django 3.2.16 on 2022-12-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_deleted_at_remove_group_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
