# Generated by Django 3.2.16 on 2022-12-17 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_tag_id_like_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
